---
- name: Ansible Provisioner for Vagrant
  hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_user: vagrant
    current_java: "java-21"
  tasks:
    - name: Install base apps
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - policycoreutils-python-utils
        - java-21-openjdk
        - java-21-openjdk-devel

    - name: Install web base apps
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
      when: inventory_hostname in groups['web']

    - name: Install db base apps
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-release-el9
        - mysql-common
      when: inventory_hostname in groups['db']

    - name: Ensure nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      when: inventory_hostname in groups['web']

    - name: Ensure mysql is running
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: true
      when: inventory_hostname in groups['db']

    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Set JAVA_HOME systemwide
      ansible.builtin.template:
        src: java_home.sh.j2
        dest: /etc/profile.d/java_home.sh
        owner: root
        group: root
        mode: '0644'

    - name: Add http to allow through firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
      when: inventory_hostname in groups['web']
    
    - name: Add mysql to allow through firewall
      ansible.posix.firewalld:
        service: mysql
        state: enabled
        permanent: true
        immediate: true
      when: inventory_hostname in groups['db']

    - name: Allow network connect for http
      ansible.posix.seboolean:
        name: httpd_can_network_connect
        state: true
        persistent: true
      when: inventory_hostname in groups['web']
